//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataEntityConn : DbContext
    {
        public DataEntityConn()
            : base("name=DataEntityConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Chapter> Chapter { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Difficulty> Difficulty { get; set; }
        public virtual DbSet<ExamZone> ExamZone { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<LogLogin> LogLogin { get; set; }
        public virtual DbSet<LogPractice> LogPractice { get; set; }
        public virtual DbSet<LogTest> LogTest { get; set; }
        public virtual DbSet<LogTestUserAnswer> LogTestUserAnswer { get; set; }
        public virtual DbSet<PaperCode> PaperCode { get; set; }
        public virtual DbSet<Passage> Passage { get; set; }
        public virtual DbSet<PastExamPaper> PastExamPaper { get; set; }
        public virtual DbSet<QuestionFORGeneral> QuestionFORGeneral { get; set; }
        public virtual DbSet<QuestionType> QuestionType { get; set; }
        public virtual DbSet<StationMail> StationMail { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<SuggestionKeyword> SuggestionKeyword { get; set; }
        public virtual DbSet<Syllabus> Syllabus { get; set; }
        public virtual DbSet<UserAuthority> UserAuthority { get; set; }
        public virtual DbSet<UserCreatePaper> UserCreatePaper { get; set; }
        public virtual DbSet<UserCreatePaperQuestione> UserCreatePaperQuestione { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UserRank> UserRank { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserScoreDetail> UserScoreDetail { get; set; }
        public virtual DbSet<VerifyStatus> VerifyStatus { get; set; }
    }
}
