//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogLogin
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LogLoginTime { get; set; }
        public Nullable<System.DateTime> LogLogoutTime { get; set; }
        public string LogLoginIp { get; set; }
        public string LogLoginOperatiionSystem { get; set; }
        public string LogLoginWebServerClient { get; set; }
        public string Remark { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
