//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogTest()
        {
            this.LogTestUserAnswer = new HashSet<LogTestUserAnswer>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int UserCreatePaperId { get; set; }
        public System.DateTime LogTestStartTime { get; set; }
        public Nullable<System.DateTime> LogTestEndTime { get; set; }
        public int LogTestScore { get; set; }
    
        public virtual UserCreatePaper UserCreatePaper { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTestUserAnswer> LogTestUserAnswer { get; set; }
    }
}
