//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaperCode()
        {
            this.PastExamPaper = new HashSet<PastExamPaper>();
            this.QuestionFORGeneral = new HashSet<QuestionFORGeneral>();
            this.Syllabus = new HashSet<Syllabus>();
            this.UserCreatePaper = new HashSet<UserCreatePaper>();
        }
    
        public int Id { get; set; }
        public int LevelId { get; set; }
        public int SubjectId { get; set; }
        public int Code { get; set; }
        public string ChineseName { get; set; }
        public int PaperCodePassScore { get; set; }
        public int PaperCodeTotalScore { get; set; }
        public int TimeRange { get; set; }
        public string PaperCodeRemark { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PastExamPaper> PastExamPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionFORGeneral> QuestionFORGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Syllabus> Syllabus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCreatePaper> UserCreatePaper { get; set; }
    }
}
