//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionFORGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionFORGeneral()
        {
            this.Comment = new HashSet<Comment>();
            this.LogPractice = new HashSet<LogPractice>();
            this.LogTestUserAnswer = new HashSet<LogTestUserAnswer>();
            this.QuestionFORDanxuan = new HashSet<QuestionFORDanxuan>();
            this.QuestionFORPanduan = new HashSet<QuestionFORPanduan>();
            this.UserCreatePaperQuestione = new HashSet<UserCreatePaperQuestione>();
            this.VerifyStatus = new HashSet<VerifyStatus>();
            this.VerifyStatus1 = new HashSet<VerifyStatus>();
        }
    
        public int Id { get; set; }
        public int QuestionType { get; set; }
        public string QuestionTitle { get; set; }
        public string Explain { get; set; }
        public string ImagePath { get; set; }
        public int DifficultyId { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpLoadTime { get; set; }
        public int VerifyTimes { get; set; }
        public bool IsDelte { get; set; }
        public int IsSupported { get; set; }
        public int IsDeSupported { get; set; }
        public int PaperCodeId { get; set; }
        public int ChapterId { get; set; }
        public Nullable<int> PastExamPaperId { get; set; }
        public Nullable<int> PastExamQuestionId { get; set; }
        public string Remark { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Difficulty Difficulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogPractice> LogPractice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTestUserAnswer> LogTestUserAnswer { get; set; }
        public virtual PaperCode PaperCode { get; set; }
        public virtual PastExamPaper PastExamPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionFORDanxuan> QuestionFORDanxuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionFORPanduan> QuestionFORPanduan { get; set; }
        public virtual QuestionType QuestionType1 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCreatePaperQuestione> UserCreatePaperQuestione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerifyStatus> VerifyStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerifyStatus> VerifyStatus1 { get; set; }
    }
}
