//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionFORPassage
    {
        public int QuestionFORPassageId { get; set; }
        public int QuestionFORPassageExtendDanxuanId { get; set; }
        public Nullable<int> PassageId { get; set; }
    
        public virtual Passage Passage { get; set; }
        public virtual QuestionFORDanxuan QuestionFORDanxuan { get; set; }
    }
}
