//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationMail
    {
        public int Id { get; set; }
        public Nullable<int> StationMailParentId { get; set; }
        public int StationMailTO { get; set; }
        public int StationMailFrom { get; set; }
        public string StationMailContent { get; set; }
        public Nullable<System.DateTime> StationMailSendTime { get; set; }
        public bool StationMailIsReaded { get; set; }
        public Nullable<System.DateTime> StationMailReadTime { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
