//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syllabus
    {
        public int Id { get; set; }
        public int PaperCodeId { get; set; }
        public int ChapterId { get; set; }
        public string SyllabusRemark { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual PaperCode PaperCode { get; set; }
    }
}
