//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAuthority()
        {
            this.UserScoreDetail = new HashSet<UserScoreDetail>();
        }
    
        public int Id { get; set; }
        public int AuthorityId { get; set; }
        public int UserGroupId { get; set; }
        public int UserRankId { get; set; }
        public string UserAuthoriryRemark { get; set; }
    
        public virtual Authority Authority { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual UserRank UserRank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserScoreDetail> UserScoreDetail { get; set; }
    }
}
