//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHTCC.EDU.CN.Onlinetest.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCreatePaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserCreatePaper()
        {
            this.LogTest = new HashSet<LogTest>();
            this.UserCreatePaperQuestione = new HashSet<UserCreatePaperQuestione>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PaperCodeId { get; set; }
        public int DifficultyId { get; set; }
        public System.DateTime UserCreatePaperTime { get; set; }
    
        public virtual Difficulty Difficulty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogTest> LogTest { get; set; }
        public virtual PaperCode PaperCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCreatePaperQuestione> UserCreatePaperQuestione { get; set; }
        public virtual Users Users { get; set; }
    }
}
